[qt]
GUIEffects=none
KDE\contrast=5
KWinPalette\activeBackground=#24273a
KWinPalette\activeBlend=#cad3f5
KWinPalette\activeForeground=#cad3f5
KWinPalette\activeTitleBtnBg=#1e2030
KWinPalette\frame=#1e2030
KWinPalette\inactiveBackground=#181926
KWinPalette\inactiveBlend=#a5adcb
KWinPalette\inactiveForeground=#a5adcb
KWinPalette\inactiveFrame=#1e2030
KWinPalette\inactiveTitleBtnBg=#1e2030
Palette\active=#cad3f5, #363a4f, #393d5c, #2e314a, #11121b, #1a1c2a, #cad3f5, #ffffff, #cad3f5, #24273a, #1e2030, #0c0d13, #957bbd, #ffffff, #c6a0f6, #c6a0f6, #1e2030, #000000, #24273a, #cad3f5, #cad3f5
Palette\disabled=#aaabb4, #424660, #464a6b, #3b3f5b, #1a1c28, #292c3e, #aaabb4, #ffffff, #aaabb4, #33374f, #2f3247, #13141d, #2f3247, #aaabb4, #9a97ae, #9a97ae, #2f3247, #000000, #24273a, #cad3f5, #cad3f5
Palette\inactive=#cad3f5, #363a4f, #393d5c, #2e314a, #11121b, #1a1c2a, #cad3f5, #ffffff, #cad3f5, #24273a, #1e2030, #0c0d13, #3b324d, #cad3f5, #c6a0f6, #c6a0f6, #1e2030, #000000, #24273a, #cad3f5, #cad3f5
font="Noto Sans,10,-1,5,50,0,0,0,0,0,Regular"
