[preferences]
show missing files = 0

[application picker]
show hidden = 0
left = 326
top = 257
width = 528
height = 245

[create folder]
left = 444
top = 334
width = 292
height = 91

[main]
left = 190
top = 222
width = 800
height = 316

