#!/bin/sh
cd ~
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM="wayland;xcb"
export CLUTTER_BACKEND="wayland"
export GDK_BACKEND="wayland,x11"
#export AMD_VULKAN_ICD=RADV
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export MANGOHUD=0
export XCURSOR_THEME=Catppuccin-Macchiato-Rosewater-Cursors
export XCURSOR_SIZE=24
export SDL_VIDEODRIVER=wayland
export GTK_THEME=Catppuccin-Macchiato-Pink
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=gtk2
export KITTY_ENABLE_WAYLAND=1
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1
export ALTERNATE_EDITOR=""
export EDITOR="nvim"                  # $EDITOR opens in terminal
export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
exec Hyprland
