#!/bin/sh
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
#export AMD_VULKAN_ICD=RADV
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export MANGOHUD=0
export XCURSOR_THEME=Catppuccin-Macchiato-Rosewater-Cursors
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=gtk2
export KITTY_ENABLE_WAYLAND=1
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1
export VISUAL="/usr/bin/emacsclient -c"
exec sway
