#!/bin/sh
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export MANGOHUD=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export KITTY_ENABLE_WAYLAND=1
#export WLR_NO_HARDWARE_CURSORS=1
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
export XDG_CURRENT_DESKTOP=sway
exec sway
