[/home/petergriffin/Downloads/Win10_21H2_English_x64.iso]
express-install=true
username=Justin
product-key=

[/home/petergriffin/Documents/Linux ISOs/Win10_21H2_English_x64.iso]
express-install=true
username=Justin
product-key=
