#Window Rules

windowrule=workspace 2,^(discord)$
windowrule = tile,^(Spotify)$
windowrulev2 = float,class:^(Anki)$,title:^(Browse)(.*)$
windowrule=float,^(catfish)$
windowrule = float, ^(pavucontrol)$
windowrule = center, ^(pavucontrol)$
windowrule = size 800 500, ^(pavucontrol)$
windowrulev2 = size 1260 1420, class:^(Anki)$,title:^(Browse)(.*)$
windowrulev2 = float,class:^(Steam)$,title:^(Friends List)(.*)$
windowrulev2 = size 391 1225,class:^(Steam)$,title:^(Friends List)$
windowrule = idleinhibit focus,^(steam_app)(.*)$
windowrule = size 1 1 ,title:^(http://localhost:)(.*)(is sharing a window.)$
windowrule = move 0 0 ,title:^(http://localhost:)(.*)(is sharing a window.)$
windowrule = size 0 0 ,title:^(http://localhost:)(.*)(is sharing a window.)$
windowrule = opacity 0 ,title:^(http://localhost:)(.*)(is sharing a window.)$
